### ISSUE TITLE
没有配置任何域名时，使用 list 命令会报错

### ISSUE THREAD

**Issue by huhubun** [huhubun/DDNSSharp#6]
- 平台
  - Windows
- 输入
  - `.\ddnssharp.exe list`
- 输出 
```
Unhandled exception. System.InvalidOperationException: Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at System.Linq.Enumerable.Max[TSource](IEnumerable`1 source, Func`2 selector)
   at DDNSSharp.Commands.Helpers.ListCommandHelper.WriteDomainConfigItemListToConsole(List`1 configs, TextWriter output) in D:\a\DDNSSharp\DDNSSharp\src\DDNSSharp\Commands\Helpers\ListCommandHelper.cs:line 15
   at DDNSSharp.Commands.ListCommand.OnExecute(CommandLineApplication app, IConsole console) in D:\a\DDNSSharp\DDNSSharp\src\DDNSSharp\Commands\ListCommand.cs:line 16
--- End of stack trace from previous location where exception was thrown ---
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.Invoke(MethodInfo method, Object instance, Object[] arguments)
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.OnExecute(ConventionContext context, CancellationToken cancellationToken)
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.<>c__DisplayClass0_0.<<Apply>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync(String[] args, CancellationToken cancellationToken)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at DDNSSharp.Program.Main(String[] args) in D:\a\DDNSSharp\DDNSSharp\src\DDNSSharp\Program.cs:line 23
```
- 预期
  - 不报错

**Comment by huhubun** [comment]
fixed
